env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-console: 0