version: 2.1

commands:
  run-all:
    steps:
      - checkout
      - run:
          command: npm ci || npm install
      - run:
          command: npm run lint

  publish:
    steps:
      - run:
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          command: npm publish

jobs:
  test-v8:
    docker:
      - image: node:8.10
    steps:
      - run-all

  test-v10:
    docker:
      - image: node:10
    steps:
      - run-all

  test-v11:
    docker:
      - image: node:11
    steps:
      - run-all

  publish-v8:
    docker:
      - image: node:8
    steps:
      - run-all
      - publish

workflows:
  test-deploy:
    jobs:
      - test-v8:
          filters:
            tags:
              only: /^v.*/

      - test-v10:
          filters:
            tags:
              only: /^v.*/

      - test-v11:
          filters:
            tags:
              only: /^v.*/

      - publish-v8:
          requires:
            - test-v8
            - test-v10
            - test-v11
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
